### ISSUE TITLE
Support for sparse vectors

### ISSUE THREAD

**Issue by hadim** [vdaas/vald#1180]
We are considering using vald for an internal project. I had a couple of questions about vald:

- Can vald handle sparse vector efficiently? The vector we are working with contains from 0-1% of `1` value (binary vectors). The architecture page mentions "compressed vector" so maybe the compression used is already efficient according to the type of vector used?
- Have you already scaled vald to an index of 5-10 billion vectors?
- Can a single deployed vald instance deal with multiple types of indexes? Let's say one sparse binary of size 512 and another one continuous float16 of size 128. This setup example will have two separate indexes (associated with two different distance types) and a request could choose only of them.
- What type is allowed for the ID/UUID of the vectors? Ideally, we would be using a custom UUID made of ASCI characters of size 27.
- It's not clear from the doc and diagram whether the index vectors is stored and backup to a database (Cassandra, Scylla, etc) or on GCS.

Thanks. Vald looks like a really nice project!

**Comment by kpango** [comment]
Hi @hadim, thanks for your interest! 

I'm Yusuke Kato (@kpango) from Vald team's tech-lead and very sorry for the late reply.
I will answer your questions one by one.

First, whether Vald supports sparse vectors, there is no interface to receive the Sparse Value index, but it can be converted to the same format as dense vectors and CRUD processing.
However, Vald is designed to achieve maximum performance when using Dense Vectors, so the Search and CreateIndex (which is done internally) may be slow.
Vald was originally designed to handle the scale of Yahoo! Japan's data, which is why billion scales have benchmarked it so that you can use it without any problems.
Vald currently supports only one Index Type (distance-type, dimension) per cluster.
Vald's Metadata (ID/UUID) can be any user-defined String, and Vald does not contract these.
On the other hand, if the size of Metadata is large, it is recommended to deploy with Meta-gateway enabled. In this case, Metadata sent from the user will be converted to UUID, and the pair will be recorded in an external DB (Redis, MySQL, Cassandra) and converted to a 12-byte unique string inside Vald.

I apologize for the lack of documentation about the external database.

You can work without using a third-party database, as Vald only provides much architecture to its users.

There are three use case to use a third-party database.

1. If you want to have external Metadata (Redis, MySQL, Cassandra)

We implemented this feature due to requests from internal users who wanted to retrieve Metadata stored in Vald from interfaces other than Vald (Redis, MySQL, Cassandra).

2. If you want to have a raw Payload Backup store Externally. (MySQL, Cassandra)

In some cases, the vector search engine is required to re-index all the data due to changes in the vector space distribution caused by changes in the machine learning model, so we keep the raw data of the CRUD process and make it possible to refer to the past raw data when re-indexing from a third party database (MySQL, Cassandra).

3. If you want to improve fault tolerance. (AWS S3, GCS)

First Vald is designed based on Yahoo! Japan scale fault tolerance.
Second, Vald stores distributed indexes in node-local storage.
This means Vald doesn't require object storage (S3, GCS) by default.
However, if that storage fails or the Datacenter fails, the index data can't be recovered quickly, and appliance storage is often the solution, but it is costly.
Therefore, Vald keeps the index data copied to S3 or GCS as an asynchronous background process to recover quickly from another region in case of failure automatically.

If you have any more questions, please feel free to ask!
We also have a slack channel. Please join.
https://join.slack.com/t/vald-community/shared_invite/zt-db2ky9o4-R_9p2sVp8xRwztVa8gfnPA

**Comment by kpango** [comment]
@hadim Did you resolve the issue? If it has been resolved, I will close this Issue.

**Comment by hadim** [comment]
Thank for your answer. I'll make a new issue if I have more questions (maybe consider openin a GH Discussion forum?).
