### ISSUE TITLE
Examples for using pre-trained models to compute vector embeddings?

### ISSUE THREAD

**Issue by sayakpaul** [vdaas/vald#1291]
Hi folks. 

`vald` looks like an amazing solution for an image similarity search pipeline I am working on. In our current pipeline, we are using a pre-trained image model to represent images as embedding vectors so that we could use those to perform _semantic_ similarity searches.  [This](https://cloud.google.com/architecture/building-real-time-embeddings-similarity-matching-system) is roughly what we are following. 

I was wondering what would be the best approach here for us to incorporate `vald`. I apologize if this is a very naive question.

**Comment by kpango** [comment]
Hi, I'm kpango from the Vald team.

Thank you for your interest in Vald.
I hope my answer will be helpful for you.

Since you mentioned that you already have a pipeline to generate embedding vectors, you can assign user-defined IDs to these  @vectors, save them in Vald by using Insert with the vector index, and Search and SearchByID on Vald to perform similarity Search, and SearchByID can be performed on Vald to perform similarity search.
Suppose you are querying an image that has already been Inserted. In that case, you can use SearchByID to search by ID since it has already been indexed. Furthermore, Search search for vectors by creating embedded vectors from an unknown image. Both operations return a list of IDs ordered by distance.
The user-defined IDs can be any unique and identifiable Unicode string.

Also, when processing large VectorIndexes, the StreamAPI such as StreamInsert, StreamUpdate, StreamUpsert, and StreamDelete can be used to minimize handshaking other overhead.

**Comment by sayakpaul** [comment]
Thanks for replying back. If you mention a couple of resources that might be relevant here (task-wise) that would be great. 

If I understood your point correctly, our best bet to introduce `vald` in our pipeline would start from serializing the embeddings inside `vald`. Correct?

**Comment by vankichi** [comment]
Hi, @sayakpaul . Sorry for late replying.

> If I understood your point correctly, our best bet to introduce vald in our pipeline would start from serializing the embeddings inside vald.

If the `serializing` means that adding unique `id` for each vector before inserting Vald, you are right.
[This blog post](https://vdaas-vald.medium.com/a-super-easy-way-to-try-similarity-search-using-vald-88fd7e8b87e9) is  a good example for use embedding data with Vald.

**Comment by sayakpaul** [comment]
By serialization, I mean saving a dictionary of unique ids and their corresponding embeddings.

**Comment by vankichi** [comment]
@sayakpaul 
That looks good !

**Comment by sayakpaul** [comment]
Okay, thank you.

**Comment by vankichi** [comment]
Please feel free to ask whenever if you have any problems.

We're also welcome to join [Vald Slack](https://join.slack.com/t/vald-community/shared_invite/zt-db2ky9o4-R_9p2sVp8xRwztVa8gfnPA).
