### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by arita37** [vdaas/vald#1521]
Hello,

Just wondering the performance
of Vald for standard top-k dataset ?

is it around 20k queries/sec for 0.8 recall ?

thanks

**Comment by kpango** [comment]
We cannot give you a general answer such as 0.8 Recall at 20kqps because performance of Vald depends on the features of vector space, data size, Vald cluster size, machine specs, etc.

I don't know what the standard top-k data set means, but I think the fastest way to find out is to try it on your environment.
Please refer to the tutorial below to deploy and benchmark your environment.
https://vald.vdaas.org/docs/tutorial/get-started/

Thank you.

**Comment by kpango** [comment]
No response for two months, so I'm going to close this PR.
