### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by pngmafia** [vdaas/vald#1532]
### Describe the bug:

I've been trying to test the memory usage of the vald standalone docker container.
 
Experiment:  To test if the memory usage of the container keeps going up?
So I've started a steady load of 10 ops/sec and started collecting the docker stats. 

I have a few queries regarding it
1. After the indexing is done the previously indexed vectors should be removed from the memory and the mem usage should come down, right? 
But that's not the case the mem usage keeps on going up

2. When the indexing happens does it happen on all the vectors inserted till that point or just a new set of batches?

3. Can vald support a constant load of requests forever? Assuming the disk is unlimited but the memory and CPU resources are limited? 

The main reason for this experiment is to see if the memory usage ever gets saturated because the memory recourse can't be kept added all the time.

All of this is assuming search request latency is not a constraint at all.

**Comment by kevindiu** [comment]
@pngmafia
Hi, thank you for your question :)

1. Vald has in-memory index architecture. It means that all the inserted vectors are always stored in memory. If the vector keep inserting to Vald, the index of the vectors will not be deleted unless the delete API is called, so the memory usage keeps going up as the number of index become larger and larger.
FYI, in Vald, the memory fragmentation issue happens due to the C api memory leak when the index operation is executed on Vald core. It means that in some case, even if the index is deleted via delete API, it may have chance that part of the memory may not be fully release.
To workaround the memory fragmentation issue, enable the index backup feature on the Vald agent and restart the Vald agent container manually if the memory fragmentation issue occurred.

2. The index happens on just a new set of batches, but the indexing time may affected by the batch size, vector dimension, and the value of the vector data. The indexing interval (auto_index_check_duration) and batch size (auto_index_length) can be set on the Vald agent for different needs. 

3. It depends on what kind of request (insert, update, search) and the volume of the request. The indexes is loaded on memory to ensure the performance of Vald. 
If consider this use case, we assume that you may deploy Vald on K8s for the scalability. If the memory problem occurs, you can easily scale the Vald cluster.

**Comment by kpango** [comment]
No response for a month, so I'm going to close this PR.
