### ISSUE TITLE
Does Vald Support GPU based Vector Similarity (DotProduct) and Filtering

### ISSUE THREAD

**Issue by astar10239** [vdaas/vald#1550]
Hi,

I am exploring vald db, and wanted to check if it supports GPU based Vector Similarity (Our Index size is 50m+ 256 dimension) so needed GPU based similarity for real time similarity on dot product.

Also wanted to filter the search of top-k with additional paramters like ids in ['1', '2'].

**Comment by kpango** [comment]
@astar10239 Hi
I'm kpango from Vald team.
Thank you for interest in Vald

I think it is early to think that a GPU is needed for real-time search with that amount of data.
Yahoo Japan uses 100 million vectors of 700 dimensions to perform real-time additions, deletions, and similarity searches in their EC image search.

On the other hand, we are planning to support Faiss because some users want to use Faiss, and it is possible to support Faiss GPU as an extension.

For filtering, it is possible to embed filtering process in Vald request route as a Plugin by implementing filtering interface for User in the form of Egress Filter (post-filter), but this is not pre-filter in ANN.

**Comment by astar10239** [comment]
Oh,

Actually faiss-gpu on gpu for 25m embb as a search time of 100-150ms, same thing is not possible with faiss-cpu on memory so thats the reason

**Comment by kpango** [comment]
I see, but Vald uses NGT for core algorithm I think the benchmark result will be different from faiss-cpu.
and search performance in vald is depends on machine spec and deployment spec.
First, I strongly recommend try vald in your environment. 
and we can help you about deployment tuning.

**Comment by kpango** [comment]
FYI, This is a part of the dashboard in our production cluster.
<img width="1627" alt="スクリーンショット 2022-02-15 14 49 49" src="https://user-images.githubusercontent.com/9798091/154000657-644f0362-5f9c-4cea-bfff-cece6ccd9b26.png">
