### ISSUE TITLE
Cassandra / ScyllaDB support

### ISSUE THREAD

**Issue by zseta** [vdaas/vald#2155]
### Is your feature request related to a problem? Please describe.:
I noticed in V1.1 Vald still had ScyllaDB backup support but it got removed in more recent versions. I couldn't find why it was removed though. Is there any plan to add Cassandra / ScyllaDB support back in?

**Comment by kpango** [comment]
In the past, Vald used ScyllaDB as a backup destination for data, however, the modern Vald uses Kubernetes' PersistentVolume for Primary Backup and supports backup to S3 compatible ObjectStorage as an additional backup destination. 

ScyllaDB is not supported in the current version of Vald since the current specification is more stable and resource efficient than backup to ScyllaDB, which requires an external connection.
