### ISSUE TITLE
Missing usage examples in Readme + first beta release date?

### ISSUE THREAD

**Issue by mkoa** [vdaas/vald#283]
High Vald team!

First of all, congrats for the great project!

I work for a major video game company. My team is involved in the development of an in-house NLP tech.

We have been following progress on NGT and Vald for the past few months and we’ve got very strong results in our benchmarks!

I was wondering if you could share any thought on when Vald will get its first official release? I can see you’re actively developing it at the moment, but I could not find any documentation to test it so far.

Also, could you add a few usage examples to the Readme file?

Thank you very much for the great work again!

**Comment by kpango** [comment]
Hello @mkoa.

I am kpango from the Vald core team. Founder of Vald and NGTD.
Thank you for contacting us.

First of all I'll tell you a short history about NGTD, Yahoo Japan Corp. uses NGTD as a similar search engine for images and text and some of our data, but NGTD was made by my hobby project, and there are many problems such as scalability, code quality, performance, sudden death, etc.  That's why we created vald for large scale of future vector search engines.

In this spring, we will release the rc version of Vald to internal users (yahoo japan employees), and I received some request from out side of our company like you. 
So we're now planning to release Vald v1 before this summer.

And we are working on the documentation you mentioned. Soon the first version of the starting document will be published soon and can be found at #230 .

**Comment by mkoa** [comment]
Hi @kpango,

Thank you very much for the swift reply.
This is very good news, thanks for considering sharing your work!

We’ll be closely watching the evolution of this repo then! This is exciting!

Thanks again

**Comment by kpango** [comment]
Hi @mkoa 

Today we published early version of the Get-Started document and add description to Readme please check it!
https://github.com/vdaas/vald#what-is-vald
https://github.com/vdaas/vald/blob/master/docs/user/get-started.md
